<?php include('includes/meta.php'); ?>
<!doctype html>
<html amp lang="en">
	<head>
		<?php include('includes/head.php') ?>
		
		 <!-- <script async src="https://cdn.ampproject.org/v0.js"></script> -->
   		<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
   		<script async custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js"></script>
	</head>
	<body>
        <?php include('includes/header.php'); ?>
        <div class="mt-breadcrumb breadcrumbs">
            <div class="container">
                <p><span><a href="index.php">Home</a></span> <span><amp-img height="12" width="12" src="../img/arrow-point-to-right.png"></amp-img></span> <span>Terms of Use</span></p>
            </div>
        </div>
        <section class="terms-of-use">
            <div class="container py-7">
                <h1>Terms of Use</h1>
                <p class="pb-3 revise-date">Last Revised: August 20, 2018</p>

                <h4>Services</h4>
                <p>Thank you for selecting the services offered to you by Alberta Payments LLC and/or its subsidiaries ("Alberta Payments LLC," "we," "our," or "us"), on this website. These General Terms of Service together with Alberta Payments LLC's Privacy Statement provided to you on the website or documentation for the Alberta Payments LLC services you have selected and the Additional Terms and Conditions for the Services (collectively, the "Agreement") govern your use of this website and the Alberta Payments LLC online services to which you are granted access under this Agreement, including but not limited to programs, components, internet-based services, content, technology, tools, updates, help content, and new releases (collectively, the "Services"). This Agreement constitutes a legal agreement between you ("you" or "your") and Alberta Payments LLC By clicking "I AGREE" and/or accessing or using the Services, you indicate that you understand and agree to the terms of this Agreement. If you do not agree to the terms of this Agreement, you are not granted any rights in the Services, and you will not be able to access or use the Services. Your access to or use of any Services may also be subject to your acceptance of separate agreements with Alberta Payments LLC and/or third parties. This Agreement incorporates by reference applicable program, subscription, activation, ordering and pricing terms provided to you online or offline for the Services selected by you and for other Alberta Payments LLC services made available to you through these Services, which may be subject to change from time to time. These terms will also govern your continued purchase and use of the Services, including such additional Alberta Payments LLC internet based services made available to you through the Services you have selected.</p>

                <h4>License Grant & Restrictions</h4>

                <p>Subject to the terms of this Agreement and any applicable payments, Alberta Payments LLC grants you a personal, limited, nonexclusive, non-transferable license, during the initial term of the subscription and any applicable renewal term or other period of use provided in the activation and ordering terms, to access and use the Services, solely for the purpose described in the Alberta Payments LLC description for the Services, and, if applicable, solely by such number of authorized users for which the applicable fee has been paid by you.</p>

                <p>Except as expressly permitted herein or by applicable law, you must not, nor allow a third party to, do any of the following:</p>
                <ul>
                    <li>license, sublicense, copy, assign, lease, loan, sell, resell, republish, upload, post, transfer, distribute or commercially exploit to any third party the Services.</li>
                    <li>modify or create derivative works based on the Services or its content, in whole or in part.</li>
                    <li>access or attempt to access any other Alberta Payments LLC systems, programs, features or data that are not made available in the Services or for public use.</li>
                    <li>de compile, disassemble, or reverse engineer the Services.</li>
                    <li>interfere with the proper working of the Services, prevent access to or the use of the Services by other licensees or customers, or impose an unreasonable or disproportionately large load on Alberta Payments LLC's infrastructure. Or</li>
                    <li>use the Services except as expressly allowed under this Agreement. By using the Services, you warrant to Alberta Payments LLC that you will not use the Services, including content, for any purpose that is unlawful or prohibited by this Agreement. If you violate any of these terms, your permission to use the Services automatically terminates. All license transfers are subject to written approval by Alberta Payments LLC and may be subject to a transfer fee determined by Alberta Payments LLC in its sole discretion. If your company is, or substantially all of its assets are, acquired by or merged into another company or sole proprietorship, please contact Alberta Payments LLC via email at <a href="mailto:info@albertapayments.com">info@albertapayments.com</a> regarding the transfer of your license to a new company.</li>
                </ul>

                <h4>Reservation of Rights & Ownership</h4>

                <p>The Services are licensed not sold, and Alberta Payments LLC reserves all rights not expressly granted to you in this Agreement. The Services are protected by copyright, trade secret and other intellectual property laws. Alberta Payments LLC and its licensors, where applicable, own all right, title and interest in and to the Services (and all intellectual property rights therein), including but not limited to its technology, content, derivatives, and modifications of the Services by whomever made. Alberta Payments does not grant any license or other authorization to any user of its branding, trademarks, service marks, or other copyrightable material or other intellectual property.</p>

                <h4>Fees</h4>

                <p>If the Services are purchased by you on a payment or subscription basis, as selected by you, the following terms will apply to you. Payments are paid in U.S. dollars and credit cards will be charged in U.S. dollars unless otherwise indicated in program ordering and pricing terms provided to you on the website and/or in the program terms for the Services you have selected. The Services will be deemed accepted by you upon acceptance of this Agreement for trial versions (if applicable) of the Services and upon acceptance of this Agreement and payment of the applicable fees and/or subscription fees for paid for versions of the Services. Access to the Services will begin:</p>
                <ul>
                    <li>for trial versions after your acceptance of this Agreement and after Alberta Payments LLC receives and processes all the information requested in the registration process; and</li>
                    <li>for paid versions after your acceptance of this Agreement and after Alberta Payments LLC receives and processes all the information, including the credit card or bank account information requested by the registration or ordering process. You must have a valid credit card or a valid debit card acceptable to Alberta Payments LLC with an appropriate logo ("Card") or sufficient funds in a checking or savings account to cover an electronic debit of the fees to obtain access to the Services. The payment information you provide must be accurate, current and complete, and you agree to notify us promptly of any change in the payment information. When you subscribe and provide payment information, your Card or bank account will be debited, and will be automatically re-debited at the beginning of each applicable monthly or one-year subscription term ("Renewal Term") at the then-current subscription rate to maintain access to the Services. Cancellation and renewal terms may be supplemented by program terms provided to you in writing or on the website for the Services you have selected.</li>
                </ul>
                <h4>Registration</h4>

                <p>Your registration information to use the Services must be accurate, current and complete as prompted in the sign-up process (the "Registration Data"). If you provide any Registration Data that is not accurate, current or complete, and do not promptly update your Registration Data, or Alberta Payments LLC has reasonable grounds to suspect it is not accurate, current or complete, Alberta Payments LLC may, in its sole discretion, suspend or terminate your account and refuse any current or future access and use of the Services or portion.</p>

                <h4>Privacy</h4>

                <p>For details about Alberta Payments LLC's privacy policies, please refer to the Privacy Statement contained in the Services you have selected, or provided to you as a link based on the Services you have selected, or the privacy policy provided on the Alberta Payments LLC website relating to the Services you have selected. You agree to be bound by the applicable Alberta Payments LLC privacy policy, as amended from time to time in accordance with its terms.</p>

                <h4>Communication</h4>
                <h6>COMMUNICATION, CONDUCT, CONTENT IF</h6>
                <p>The Services may include a feature that allows you to exchange helpful information with other users of the Services and the public. Internet access is required to use these communication facilities. Please respect and interact with other users as you would in any public arena when using such features. You are responsible for exercising your judgment in evaluating and acting on (or ignoring) other users' communication sessions. Alberta Payments LLC does not endorse and is not responsible for the accuracy of the content in these facilities, and will not be liable for any damages incurred as a result of the submission, viewing or use of any such content. Users may post hypertext links to content hosted and maintained by third parties. Alberta Payments LLC has no obligation to monitor these linked sites, and is not responsible for them. Your access to any linked sites is at your own risk. Do not reveal information that you do not want to make public. You also agree to comply with applicable Alberta Payments LLC discussion board policies made available to you for the Services you have selected.</p>
                <ol>
                    <li>Your right to use the Services is personal to you (and your company and its employees, if permitted by Alberta Payments LLC). You are entirely responsible and liable for all information, data, text, software, music, sound, photographs, graphics, video, messages or other materials ("Content") uploaded, posted or stored by you using the Services. You shall not use the Services for any illegal purpose in violation of any local, state, federal or international law. You must provide all required and appropriate warnings, information and disclosure, comply with all applicable laws and regulations, and take all other required and appropriate actions (collectively, "Information and Actions") in connection with your use of the Services. If the Services do not provide adequate features for you to provide such Information and Actions, then do not use the Services. You agree that you will not use the Services to share, store, or in any way distribute financial data that is not in complete accordance with the law. Any users suspected of having financial information which involves fraud, embezzlement, money laundering, insider trading, support for terrorism, or any other activity proscribed by law may have their accounts terminated, their financial data erased, and they also may be reported to law enforcement officials in the appropriate jurisdictions. Alberta Payments LLC does not own and is not responsible for the Content or data you submit on the website. You are encouraged to archive your data regularly and frequently and you bear full responsibility for archiving your data and sole liability for any lost or irrecoverable data.</li>
                    <li>You agree to defend, indemnify and hold Alberta Payments LLC, its Suppliers as defined below, its corporate affiliates, officers, directors, employees, subsidiaries and agents, harmless from and against any and all third party claims, costs, damages, losses, liabilities and expenses (Including reasonable attorney’s fees) resulting from or arising out of a claim that your Content infringes or misappropriates the intellectual property rights, or otherwise violates any other right, of a third party or a claim resulting from or arising out of your breach or alleged breach of this Agreement.</li>
                    <li>You agree that you will not use the Services to upload, post, link to, publish, distribute, reproduce or transmit any of the following:
                    <ol>
                        <li>Any unlawful, fraudulent, libellous, defamatory, obscene, pornographic, profane, threatening, abusive, hateful, offensive, inappropriate or otherwise objectionable information of any kind, Including without limitation any transmissions constituting or encouraging conduct that would constitute an attack or "flaming" other participants, or would constitute a criminal offense, give rise to civil liability, or otherwise violate any local, state, federal or foreign law; or</li>
                        <li>Any Content or data to impersonate other individuals or falsely represent your identity or qualifications, or that constitutes a breach of any individual's privacy, Including posting images about children or any third party without their consent (or a parent's consent in the case of a minor); or</li>
                        <li>Any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities or schemes or other unsolicited commercial communication (except as otherwise expressly permitted by Alberta Payments LLC) or engage in spamming or flooding; or</li>
                        <li>Any information or software which contains a virus, Trojan horse, worm or other disruptive or harmful component; or is obtained through the Services for commercial purposes (other than as expressly permitted by the provider of such information, software or other material); or</li>
                        <li>Any information, software or other material obtained through the Services which is protected by copyright, or other proprietary right, or derivative works with respect thereto, without obtaining permission of the copyright owner or right holder.</li>
                    </ol>
                    </li>
                    <li>You agree that Alberta Payments LLC has the right but not the obligation to monitor the Services and Content from time to time and to disclose any information as necessary or appropriate to satisfy any law, regulation or other governmental request, to operate the Services properly, or to protect itself or its users. Alberta Payments LLC will not intentionally disclose any private email message unless required by law. Alberta Payments LLC reserves the right to edit, refuse to post, remove or refuse to remove any information or materials, in whole or in part, that, in its sole discretion, is alleged to be unacceptable, undesirable, inappropriate or in violation of this Agreement.</li>
                </ol>
                <h4>MATERIALS PROVIDED TO ALBERTA PAYMENTS LLC OR POSTED AT ALBERTA PAYMENTS LLC WEBSITE</h4>
                <p>Alberta Payments LLC does not claim ownership of the materials you provide to Alberta Payments LLC (including feedback and suggestions) or post, upload, input or submit to any Alberta Payments LLC Web Site or its associated services (collectively “Submissions”). However, by posting, uploading, inputting, providing or submitting your Submission you are granting Alberta Payments LLC its affiliated companies and necessary sub licensees permission to use your Submission in connection with the operation of their Internet businesses including, without limitation, the rights to: copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and reformat your Submission; and to publish your name in connection with your Submission.</p>
                <p>No compensation will be paid with respect to the use of your Submission, as provided herein. Alberta Payments LLC is under no obligation to post or use any Submission you may provide and may remove any Submission at any time Alberta Payments LLC’s sole discretion.</p>
                <p>By posting, uploading, inputting, providing or submitting your Submission you warrant and represent that you own or otherwise control all of the rights to your Submission as described in this section including, without limitation, all the rights necessary for you to provide, post, upload, input or submit the Submissions.</p>

                <h4>Alberta Payments LLC Services</h4>
                <p>You may be made aware of or offered services, features, products, applications, online communities, or promotions provided by Alberta Payments LLC ("Alberta Payments LLC Services"). If you decide to use Alberta Payments LLC Services, you may be subject to additional terms and conditions governing these Alberta Payments LLC Services and separate fees may apply. You acknowledge that in accessing certain Alberta Payments LLC Services through the Services you may upload or enter certain data from your account(s) such as names, addresses and phone numbers, purchases, and sales among others, to the Internet. You hereby grant Alberta Payments LLC permission to use information about your business and usage experience to enable us to provide the Alberta Payments LLC Services to you, including updating and maintaining your data, addressing errors or service interruptions, and to enhance the types of data and services Alberta Payments LLC may provide to you in the future. You also grant Alberta Payments LLC permission to combine your business data, if any, with that of others in a way that does not identify you or any individual personally to improve services and to compare business practices with other company standards. We may use your data to create, market or promote new Alberta Payments LLC offerings to you and others.</p>

                <h4>Disclaimer-of-warranties.</h4>
                <ol>
                    <li>YOUR USE OF THE SERVICES, INCLUDING ANY SOFTWARE, AND CONTENT THEREIN, IS ENTIRELY AT YOUR OWN RISK. EXCEPT AS EXPRESSLY PROVIDED IN THIS AGREEMENT, THE SERVICES ARE PROVIDED "AS IS," AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALBERTA PAYMENTS LLC, ITS AFFILIATES, LICENSORS, THIRD-PARTY CONTENT AND SERVICE PROVIDERS, DISTRIBUTORS, RESELLERS AND SUPPLIERS (COLLECTIVELY "SUPPLIERS") DISCLAIM ALL WARRANTIES , WHETHER EXPRESS, IMPLIED, OR STATUTORY REGARDING THE SERVICES, CONTENT AND RELATED MATERIALS INCLUDING ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, MERCHANTABILITY, NON-INTERFERENCE WITH OR NON-INFRINGEMENT OF ANY INTELLECTUAL PROPERTY RIGHTS, AND SIMILAR LAWS OF ANY JURISDICTION. ALBERTA PAYMENTS LLC AND ITS SUPPLIERS DO NOT WARRANT THE ACCURACY, RELIABILITY, COMPLETENESS, USEFULNESS, QUALITY OR ANY CONTENT IN THE SERVICES, INCLUDING CONTENT POSTED ON OR LINKED FROM THE SERVICES. ALBERTA PAYMENTS LLC AND ITS SUPPLIERS DO NOT WARRANT THAT THE SERVICES ARE SECURE, FREE FROM BUGS, VIRUSES, INTERRUPTION, ERRORS, THEFT OR DESTRUCTION OR THAT THE SERVICES WILL MEET YOUR REQUIREMENTS. YOU ASSUME ALL RISKS ASSOCIATED WITH USING OR RELYING ON SUCH CONTENT. IF THE EXCLUSIONS FOR IMPLIED WARRANTIES DO NOT APPLY TO YOU, ANY IMPLIED WARRANTIES OR CONDITIONS ARE LIMITED IN DURATION TO 60 DAYS FROM THE DATE OF PURCHASE OR DELIVERY OF THE SERVICES, WHICHEVER IS SOONER.</li>
                    <li>ALBERTA PAYMENTS LLC AND ITS SUPPLIERS ARE NOT ENGAGED IN RENDERING LEGAL, FINANCIAL, ACCOUNTING OR OTHER PROFESSIONAL SERVICE. IF SUCH ASSISTANCE IS REQUIRED, THE SERVICE OF A COMPETENT PROFESSIONAL SHOULD BE SOUGHT. ALBERTA PAYMENTS LLC AND ITS SUPPLIERS EXPRESSLY DISCLAIM ANY REPRESENTATIONS OR WARRANTIES THAT YOUR USE OF THE SERVICES WILL SATISFY ANY STATUTORY OR REGULATORY OBLIGATIONS, OR WILL ASSIST WITH, GUARANTEE OR OTHERWISE ENSURE COMPLIANCE WITH ANY APPLICABLE LAWS OR REGULATIONS, INCLUDING BUT NOT LIMITED TO THE HEALTH INSURANCE PORTABILITY AND ACCOUNTABILITY ACT OF 1996 ("HIPAA"), THE GRAMM-LEACH-BLILEY ACT OF 1999, THE SARBANES-OXLEY ACT OF 2002, OR OTHER FEDERAL OR STATE STATUTES OR REGULATIONS. YOU ARE SOLELY RESPONSIBLE FOR ENSURING THAT YOUR USE OF THE SERVICES IS IN ACCORDANCE WITH APPLICABLE LAW.</li>
                </ol>
                <p>LIMITATION OF LIABILITY AND DAMAGES. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, THE ENTIRE CUMULATIVE LIABILITY OF ALBERTA PAYMENTS LLC, ITS AFFILIATES AND SUPPLIERS, AND YOUR EXCLUSIVE REMEDY FOR ALL MATTERS OR CLAIMS ARISING FROM OR RELATING TO THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT PAID BY AND/OR DUE FROM THE REGISTERED USER FOR THE SERVICES TO ALBERTA PAYMENTS LLC, ITS AFFILIATES OR ITS SUPPLIERS IN THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ALBERTA PAYMENTS LLC, ITS AFFILIATES AND ITS SUPPLIERS SHALL NOT BE LIABLE FOR ANY (A) INDIRECT, SPECIAL, IDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES; AND (B) DAMAGES RELATING TO TELECOMMUNICATION FAILURES, INTERNET AND ELECTRONIC COMMUNICATIONS FAILURES, DELAYS OR LIMITATIONS, LOSS, CORRUPTION, SECURITY OR THEFT OF DATA, VIRUSES, SPYWARE, LOSS OF BUSINESS, REVENUE, PROFITS OR INVESTMENT, USE OF SOFTWARE OR HARDWARE THAT DOES NOT MEET ALBERTA PAYMENTS LLC SYSTEMS REQUIREMENTS, TAX POSITIONS TAKEN BY YOU; ARISING OUT OF OR CONNECTED IN ANY WAY WITH THE SERVICES, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF ALBERTA PAYMENTS LLC, ITS AFFILIATES AND ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN ALBERTA PAYMENTS LLC AND YOU. ALBERTA PAYMENTS LLC WOULD NOT HAVE PROVIDED THIS SOFTWARE WITHOUT SUCH LIMITATIONS.</p>

                <h4>Amendment</h4>
                <p>Alberta Payments LLC may change this Agreement from time to time effective upon posting of the modified Agreement on its website. Please review the Agreement periodically on this website for changes. Alberta Payments LLC has the right to change or add to the terms of this Agreement, and to change, delete, discontinue, or impose conditions on any feature or aspect of the Services, Including but not limited to, Internet based services, pricing, technical support options, and other product-related policies, upon reasonable notice, Including but not limited to posting information concerning such change in the Services selected by you or on an Alberta Payments LLC sponsored website. Your continued use of the Services after Alberta Payments LLC's publication of any such changes shall constitute your acceptance of this Agreement as modified.</p>

                <h4>Termination</h4>
                <p>Your rights under this Agreement may be terminated or suspended by Alberta Payments LLC immediately and without notice if you or any of your authorized users fail to comply with any terms of this Agreement or you no longer consent to receive electronic Communications. Upon termination you must immediately cease using the Services and all outstanding payments will become due and owing. Any termination of this Agreement shall not affect Alberta Payments LLC's rights hereunder. Alberta Payments LLC may terminate a free account at any time in its sole discretion. Other terms regarding termination or expiration of the Services may apply in accordance with the activation and ordering terms for the specific Services you have selected. If you choose to cancel your account or any part of the Services, you must do so in accordance with the activation and ordering terms for the specific Services you have selected.</p>

                <h4>Export Restrictions</h4>
                <p>You acknowledge that this website, the Services, and the software made a part of the Services are subject to U.S. export control regulations administered by the U.S. Dept. of Commerce (15 CFR, Chapter VII) and that you will comply with these regulations. You will not export or re-export the Services, directly or indirectly, in violation the U.S. export administration laws and regulations to any country or end user; or to any end user who you know or have reason to know will utilize them in the design, development or production of nuclear, chemical or biological weapons. You further acknowledge that the Services may include technical data subject to such U.S. export regulations.</p>

                <h4>Third Party Products</h4>
                <p>In connection with your use of the Services, you may be made aware of services, products, offers and promotions provided by third parties who are not affiliated with Alberta Payments LLC ("Third Party Products"). If you decide to use any Third Party Products, you do so at your own risk and are responsible for reviewing the terms governing such Third Party Products. You authorize Alberta Payments LLC to use and disclose your contact information, Including name and address, for the purpose of making the Third Party Products you choose available to you. You agree that the third party, and not Alberta Payments LLC, is responsible for the performance of the Third Party Products. The Services may contain or reference links to websites operated by third parties ("Third Party Websites"). Alberta Payments LLC is not responsible for the content of, nor any link contained in such Third Party Websites. The inclusion of any Third Party Website link in the Services is not and does not imply an affiliation, sponsorship, endorsement, approval, investigation, verification or monitoring by Alberta Payments LLC of any data contained in, or services made available through any Third Party Website. You acknowledge that linked Third Party Websites may contain terms and privacy policies that are different from those of Alberta Payments LLC expressly disclaims any liability for use of such Third Party Products and Third Party Websites.</p>

                <h4>U.S.</h4>
                <p>GOVERNMENT. The software that forms a part of the Services is a "commercial item," as that term is defined at 48 C.F.R. 2.101 (OCT 1995), consisting of "commercial computer software" and "commercial computer software documentation," as such terms are used in 48 C.F.R. 12.212 (SEPT 1995). Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7202-4 (JUNE 1995), all U.S. Government end users who access or use the Services, acquire a license to use the software with only those rights set forth herein.</p>

                <h4>Miscellaneous</h4>
                <p>This Agreement is the complete agreement between you and Alberta Payments LLC and sets forth the entire liability of Alberta Payments LLC, its corporate affiliates and its Suppliers and your exclusive remedy with respect to the Services and its use. Any modification or waiver of the terms herein by Alberta Payments LLC must be in a writing signed by an authorized representative of Alberta Payments LLC and expressly referencing the applicable provisions of this Agreement. If any provision of this Agreement is invalid or unenforceable under applicable law, then it shall be interpreted to accomplish the objectives of such provision to the fullest extent possible under applicable law, and the remaining provisions will continue in full force and effect. This Agreement may not be assigned by you without the prior written approval of Alberta Payments LLC, but may be assigned without your consent by Alberta Payments LLC to (a) a parent or direct or indirect subsidiary, (b) in an acquisition of the assets Including the Services, in whole or in part, (c) a successor by merger. Any assignment in violation of this Section will be void. This agreement will be governed by State and Federal courts located in the State of New Jersey. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement. The parties hereby consent on the exclusive jurisdiction and venue in the state courts in Middlesex County or State & Federal courts of State of New Jersey.</p>

                <p>Customers will be responsible to properly define and review departments, category, tax rates and other settings related to their price book and other areas. Alberta Payments LLC will not be liable for any loss or over payments to any party by the customer including any error which might arise in calculation of state taxes, federal taxes or payroll taxes, due to improper account settings.</p>

                <p>Any replacement request for replacement of equipment and hardware purchased through our online shopping portal, will need to be made within 10 calendar days of receiving the delivery of equipment. Alberta Payments LLC will forward same request to the distributor. Ultimate decision to replace the equipment would be with the distributor of the subject equipment. Alberta Payments LLC will not be liable for any rejection by the distributor to replace the equipment. Customer would be responsible to ship back the equipment to distributor with its original packing and complete set of parts.</p>

                <p>Alberta POS Customers opting to avail merchant account services from third party processing companies, to integrate with Alberta POS will be required to pay additional fee/charges on per terminal basis.</p>

                <p>Alberta Payments Supplemental License and Terms of Services</p>

                <p>Thank you for selecting Alberta Payments software (the "software"). This license agreement in addition to the Alberta Payments LLC Terms of Service (the "Agreement") is a legal agreement between the Licensee, a single legal entity identified in the registration process provided as part of the start-up interview ("Licensee", "you"), and Alberta Payments LLC ("Alberta Payments LLC," "we", "our" or "us").</p>

                <p>By clicking "ACCEPT", Licensee indicates that it has read and understood, and assents to be bound by, the terms of this Agreement. If the person clicking on the "ACCEPT" button is an individual working for Licensee ("Agent"), such person is agreeing to the terms and conditions of this Agreement on behalf of Licensee and certifies that he/she is an Agent of Licensee and has all necessary authority to act on Licensee's behalf, Including to bind Licensee to the terms and conditions of this Agreement.</p>

                <p>Licensee does not agree to the terms of the Agreement; Licensee is not granted any rights whatsoever in the Software. If Licensee is not willing to be bound by these terms and conditions, Licensee should not click on the "ACCEPT" button, and may not access or otherwise use the Software or Services.</p>

                <h4>SUBSCRIPTION</h4>
                <p>The Software is licensed on a monthly subscription basis, as selected by Licensee or its agent. Subscription Policy are:</p>
                <ol>
                    <li>Monthly charges applied are for the Current running month, and not for the previous month</li>
                    <li>Monthly charges will be applied to bank/credit card any date between 1-15th of the month</li>
                    <li>Data Entry Services</li>
                </ol>
                <br>
                <p>Customer has following two options to start the service</p>
                <ul>
                    <li>Start service starting from 1st day of the next month OR</li>
                    <li>Start with immediate effect, for example: if customer is signing on 8th of March, he can start service same day, but he will be charged for the full month</li>
                </ul>
                <p>There is no free/trial period for data entry.</p>
                <p>Alberta POS agreement and subscription terms and conditions supersedes this section.</p>

                <h4>CANCELLATION</h4>
                <ol>
                    <li>Any cancellation request should be submitted at least 15 business days in Advance through your email address registered with Alberta payments</li>
                    <li>Cancellation request to mention your store account number with Alberta payments/Alberta Payments ID, Store Name, Store Address, Contact number and Contact person name and Cancellation effective date. to complete the cancellation</li>
                    <li>Write: “Service Cancellation request” in subject line of the email</li>
                    <li>Send Cancellation request to this email ID only <a href="mailto:support@albertapayments.com">support@albertapayments.com</a></li>
                    <li>No telephonic/verbal instructions will be accepted for the Cancellation</li>
                    <li>Any Cancellation will be effective following month on completion of 15 days of notice period</li>
                    <li>If request is not received 15 days’ advance through email, Customer will be charged for the Following/Next Month and no refund will be provided for the charges</li>
                </ol>

                <h4>Termination By Licensee</h4>
                <p>Licensee may notify Alberta Payments LLC to cancel the subscription prior to the beginning of each Renewal Term. Licensee's rights to use the Software may be terminated by Alberta Payments LLC immediately and without notice if Alberta Payments LLC is unable to debit Licensee's or its agent's Card in accordance with this Agreement.</p>

                <h4>Permitted Disclosures and Use Of Data</h4>
                <p>Licensee acknowledges and agrees that in order to provide Licensee with access to and use of the Software and Services, Alberta Payments LLC may provide Licensee Access Information and Account Data to:</p>

                <ul>
                    <li>Licensee's employee or agent who is identified in the Registration Data as the current system administrator for the Licensee's account (the "Current Administrator"),</li>
                    <li>such other Licensee employee or agent who may be designated by Licensee as a replacement administrator for the Licensee's account by following the procedures required by Alberta Payments LLC to effectuate such replacement, and</li>
                    <li>any other person identified as an authorized user of the Software in the set-up interview form or in any subsequent communication to Alberta Payments LLC (collectively, "Information Recipients").</li>
                </ul>
                
                <p>Licensee grants Alberta Payments LLC permission to aggregate any previous and/or future uploaded, non-personally identifiable account data with that of other users of the Service. You permit Alberta Payments LLC to use that aggregated data to improve services, issue promotions, and provide ways for you to compare business practices with other users.</p>

                <h4>Software Use, Storage And Access</h4>
                <p>Alberta Payments LLC shall have the right, in its sole discretion and with reasonable notice posted on the Alberta Payments site and/or sent to Licensee at the Current Administrator's email address provided in the Registration Data, to revise, update, or otherwise modify the Services and establish or change limits concerning use of the Software and Services, temporarily or permanently, Including but not limited to:</p>
                <ul>
                    <li>the amount of storage space Licensee has on the Software at any time, and</li>
                    <li>the number of times (and the maximum duration for which) Licensee may access the Software in a given period of time. Alberta Payments LLC reserves the right to make any such changes effective immediately to maintain the security of the system or Licensee Access Information or to comply with any laws or regulations, and to provide Licensee with electronic or written notice within thirty (30) days after such change. Licensee may reject changes by discontinuing use of the Software and Services to which such changes relate.</li>
                </ul>

                <p>Licensee's continued use of the Software or Services will constitute Licensee's acceptance of and agreement to such changes. For details about our refund policy, please email us at <a href="mailto:info@albertapayments.com">info@albertapayments.com</a> or call <a href="tel:888-502-6650">888-502-6650</a>. Alberta Payments LLC may, from time to time, perform maintenance upon the Software or Services resulting in interrupted service, delays or errors in the Software or Services. Alberta Payments LLC will attempt to provide prior notice of scheduled maintenance but cannot guarantee that such notice will be provided.</p>
                </div>
            </section>
            <?php include "includes/footer.php"; ?>
    </body>
</html>        