<?php 
	function metaDetails($pageName) 
	{
		$metaArr = array( 
			 "index" => array (
               "pageTitle" => "Retail Management and POS Services for Small Businesses | Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services, Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing Service, Credit Card Machines for Small Business, merchant Services Credit Card Processing, Credit Card Payment Processing Services, merchant Credit Card Processing, Small Business Credit Card Processing, Credit Card Processing Companies , Cloud Based POS,Point of Sales, Point of Sales System, Cash Drawers, Merchant Services, ATM, Inventory Management System, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register software, POS equipment, POS terminal, Point of Sales equipment, POS Cash Register, POS machine, cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile App, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering Kiosk, Kiosk Services, Touch Screen Kiosk",	
               "metaDescription" => "Alberta Payments LLC located in New Jersey USA, provides retail management solutions like point of sale, credit card processing and food processing kiosk with key features to enhance your sales and customer experience."
            ),
            "payment-processing" => array (
               "pageTitle" => "Payment Processing Services for Small Business | Credit Card Processing Company | Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services, Payment Processing companies, Payment Processing companies USA, Credit Card Processing companies for Small Business, Online Payment Processing companies, Online Credit Card Processing, Online Payment Processing Service, Credit Card Machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Credit Card Processing companies,Merchant Services, POS, Retail Management Solutions, Card Processing Services, Payment Processing, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Quick service Restaurant Register System, No Hidden Fees, No Extra Cost, Card Processing Rates, Personalized Services, Friendly Customer Support",	
               "metaDescription" => "Looking for payment processing services companies for your business? Alberta payments LLC can fulfill all your payment processing needs. Alberta Payments provides payment and credit card processing services from small to large scale business needs across the United States."
            ), 
			"kiosk-food-ordering" => array (
               "pageTitle" => "Self Service Kiosks for Food Ordering | Online Food Ordering for Restaurants | Alberta Payments LLC | USA",
               "metaKeyword" => "Ordering Kiosk Systems, Self Ordering Kiosk, Self Payment Kiosk, Food Ordering Kiosk, Online Food Ordering System, Order Food from Kiosk, Food Self Ordering Kiosk, Self-Service Food Kiosk, Self-checkout Kiosk, Self Service Kiosks for Food Ordering, Kiosk in fast Food restaurants, Self Ordering System, Food Ordering Kiosks, Ordering Kiosk,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Looking for Food Ordering Kiosk for your restaurant business? Alberta Payments provides the solutions you need. Our kiosk helps you control cost, improves order accuracy and reduces time taken to check out by taking customer orders to eliminate traditional processes and human error. "
            ), 
			"mobile-product" => array (
               "pageTitle" => "Alberta’s Mobile App for Small Retail Businesses | Alberta Mobile App | USA",
               "metaKeyword" => "Mobile App for Small Business, Mobile Apps for Small Businesses, Small Business App, Mobile Apps for Business, Mobile App for my Business, Mobile Applications in Business, Small Business App, Alberta Mobile App , Apps for Small Business Records,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Do you want live updates about the transactions on your POS? Alberta mobile app gives the solution. Manage your business with your fingertip by using of our Mobile app. Get live updates and change the pricing of your products anytime, anywhere through our mobile app."
            ), 
			"loss-prevention" => array (
               "pageTitle" => "Loss Prevention Practices for your Small Retail Businesses | Alberta Payments LLC | USA",
               "metaKeyword" => "Loss Prevention in Retail, Retail Store Loss Prevention, Retail Loss Prevention, Retail Loss Prevention Service Provider , Retail Loss Prevention, Store Loss Prevention, preventing Retail Theft, Retail Theft, Loss Prevention in Retail Stores, Loss Prevention in Retail Stores, Loss Prevention in Retail, employee Theft in Business, Small Business employee Theft, employee Theft in the workplace, Small Business Theft, Small Business Identity Theft Protection, Identity Theft in Business, Identity Theft Protection for Businesses, Small Business Fraud Protection, Identity Theft in Business,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Alberta Payments LLC provides innovative retail loss prevention and security solutions to protect your business transactions. Our Point of sale (POS) offers loss prevention features for employee theft at your small business. You get instant alerts when there is any incident of theft."
            ), 
			"rms-pos" => array (
               "pageTitle" => "Cloud based POS Systems for Small Retail Business | Alberta Payemts LLC | USA",
               "metaKeyword" => "Cloud based POS, Retail Cloud POS , Cloud based POS Software, Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management solutions USA, Retail Management Systems POS, Retail Management solutions llc, RMS POS,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Our cloud-based Point of sale ( POS ) is the best Retail Management solutions for small to large scale businesses. Our cutting edge technology will help to reduce the risks of retail loss and employee theft."
            ), 
			"industry-relations" => array (
               "pageTitle" => "Industry Relations for Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail management Companies,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "See what industry speaks about Alberta Payments LLC here. Alberta Payments sincerely engages with industry and promote business growth for all the stakeholders."
            ), 
			"testimonials" => array (
               "pageTitle" => "Customer Testimonials about Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card Machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Check what customers say about Alberta Payments LLC. Alberta serves it customers with best of products and unmatched services always."
            ), 
			"about-us" => array (
               "pageTitle" => "About us | Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Alberta Payments LLC is a professional retail management and POS solutions company located in New Jersey, USA. We offer complete solutions to streamline your small retail business needs with the help of great product ranges and excellent customer support."
            ), 
			"news-and-events" => array (
               "pageTitle" => "News and Events | Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Get all latest news and events about Alberta Payments LLC. Know how Alberta brings innovation and growth in retail business every day."
            ), 
		
			"contact-us" => array (
               "pageTitle" => "Contact us | Alberta Payments LLC | USA",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Fill the Contact us form for all your retail management requirements. Our support team at Alberta Payments will respond soon with customized solution for you."
            ), 
			
			"careers" => array (
               "pageTitle" => "Careers | Alberta Payments LLC ",
               "metaKeyword" => "Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Alberta Payments LLC is looking for young, energetic and enthusiastic people to work for it. Interested people can drop a mail with their bio-data. "
            ), 
			
			"scan-data" => array (
               "pageTitle" => "Scan Data Program | Alberta Payments LLC ",
               "metaKeyword" => "Scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "5 mins with Alberta POS can help you earn manufacturer incentives with Scan Data Program "
            ), 
			
			"dosti" => array (
               "pageTitle" => "Dosti - Our Values | Alberta Payments LLC ",
               "metaKeyword" => "dosti, our values, Scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Dosti Alberta se dosti karlo, fayde mein rahoge "
            ), 
			
			
			"terms-of-use" => array (
               "pageTitle" => "Terms of Use | Alberta Payments LLC ",
               "metaKeyword" => "Alberta terms of use, dosti, our values, Scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Read General Terms of Service together with Alberta Payments LLC"
            ), 
			
			"privacy-policy" => array (
               "pageTitle" => "Privacy policy | Alberta Payments LLC ",
               "metaKeyword" => "Alberta privacy policy, dosti, our values, Scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Read Privacy policy ststement of Alberta Payments LLC"
            ), 
			
			
			"agent-program" => array (
               "pageTitle" => "Agent Program | Alberta Payments LLC ",
               "metaKeyword" => "Alberta agent program, be an Alberta agent, dosti, our values, Scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Stand OUT… Be Legendary! Discover A Different kind of Retail Technology Partner through our Agent Program."
            ), 
			
			
			"inventory-management" => array (
               "pageTitle" => "Inventory Management | Alberta Payments LLC ",
               "metaKeyword" => "inventory management solutions by Alberta payments, scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "SMART Inventory management system offered by Alberta POS helps you get control of your store inventory without much hassle."
            ), 
			
			"sitemap" => array (
               "pageTitle" => "Sitemap | Alberta Payments LLC ",
               "metaKeyword" => "sitemap, alberta payments website sitemap, inventory management solutions by Alberta payments, scan data program, Payment Processing Services, Credit Card Processing Services,Payment Processing Companies, Payment Processing Companies USA, Credit Card Processing Companies for Small Business, Online Payment Processing Companies, Online Credit Card Processing, Food Processing Kiosk, Food Processing Industry, Food Processing Company, Online Payment Processing service, Credit Card machines for Small Business, Merchant Services Credit Card Processing, Credit Card Payment Processing Services, Merchant Credit Card Processing, Small Business Credit Card Processing, Self Service Kiosk for Food Ordering, Ordering kiosk, App Download for Payment Processing.  Mobile Payment Processing Services, Payment apps for Business, free Online Payment Processing, Payment Processing for Online, Mobile Payment Applications, Loss prevention in Retail, Retail Store Loss prevention, Preventing Retail Theft,Loss prevention in Retail Stores,Loss prevention in Retail, Employee Theft in Business, Small Business Employee Theft,  Cloud POS Systems, Cloud based POS Systems, POS Systems for Small Business, Cloud based POS, Cloud based POS system, Retail Management Companies, Careers, Looking for Job,Point of Sales, Point of Sales System, Cash Drawers, POS, Retail Management Solutions, Card Processing Services, Payment Processing, POS Companies, Cash Register, Cash Register Software, POS Equipment, POS Terminal, Point of Sales Equipment, POS Cash Register, POS Machine, Cashier System, Grocery Store POS, Deli Store POS, Convenience Store POS, Liquor Store POS, Inventory Management, Scan Data, Touch Screen POS, Loss Prevention, Employee Theft, Quick Service Restaurant Register System, Mobile POS, Mobile app, Profit and Loss Statement, Loyalty Program, Agent Partnership Program, Free POS, Food Ordering kiosk, kiosk Services, Touch Screen kiosk
",	
               "metaDescription" => "Explore Alberta Payments website through its sitemap."
            ), 
			
						
			);
 			return @$metaArr[$pageName]; 
  	}
?>